name: SvatekPlugin
version: 1.0
main: me.monty.svatek.SvatekPlugin
api-version: '1.21'
author: Monty
description: Plugin na státní svátky pouze česko
website: https://discord.gg/Cvf4wMwmZx
depend: [PlaceholderAPI]
permissions:
  svatek.view:
    description: Umoznuje hracum videt svatek (zakladni pravo)
    default: true
